cards:
  c1:
    name: "è”¡å¾å¤"
    description: "é¸¡ä½ å¤ªç¾"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/3ae3e7e09a411aa7a1a009697fd29f81-Full.webp?w=481&h=433"
    rarity: "æ™®é€š"
  c2:
    name: "ä¸€çœ¼ä¸çœŸ"
    description: "é‰´å®šä¸ºï¼šçœŸ"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/094d224a1a9fc692ee1127864dd97273-Full.webp?w=565&h=802"
    rarity: "æ™®é€š"
  c3:
    name: "è‚–æˆ˜"
    description: ""
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/a1de70909ab25add607e299dd5ab93f5-Full.webp?w=667&h=1000"
    rarity: "åƒåœ¾"
  c4:
    name: "ä¹‰çœ¼ä¸çœŸ"
    description: "é‰´å®šä¸ºï¼šå‡"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/52bdba9958768b25dbe4da89727bddc6-Full.webp?w=688&h=857"
    rarity: "æ™®é€š"
  c5:
    name: "é»‘çŒª"
    description: "pigga"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/073a3744964c0216a6f00d7203382654-Full.webp?w=400&h=400"
    rarity: "æ™®é€š"
  c6:
    name: "å†°å¢©å¢©"
    description: ""
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/c9ed8e686401e5153d05468f43f9407d-Full.webp?w=1194&h=1278"
    rarity: "ç¨€æœ‰"
  c7:
    name: "Linus Torvalds"
    description: "So, NVIDIA, fuck you"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/11298c7e90434dc53a268b4702c42fd1-Full.webp?w=1024&h=649"
    rarity: "å²è¯—"
  c8:
    name: "ç”°æ‰€æµ©äºŒ"
    description: "å“¼ï¼å“¼ï¼å•Šå•Šå•Šå•Šå•Šå•Šå•Šå•Šå•Šå•Šå•Šï¼"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/6ab796fcc0beb521a1e28341ff478317-Full.webp?w=435&h=319"
    rarity: "å²è¯—"
  c9:
    name: "è‰"
    description: "ä¸€ç§æ–¹å—"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/6d8e53cb41fe8353ae082e139f70e4dc-Full.webp?w=126&h=58"
    rarity: "æ™®é€š"
  c10:
    name: "é™ˆç¿"
    description: "ä½ æ‰€çƒ­çˆ±çš„ï¼Œå°±æ˜¯ä½ çš„ç”Ÿæ´»"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/67f3ecfddd921e1e4ae21c80dbfcbd35-Full.webp?w=100&h=98"
    rarity: "åƒåœ¾"
  c11:
    name: "youzhi"
    description: "ğŸ˜‚"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/ba2d727edb64586d48651e721debd846-Full.webp?w=640&h=640"
    rarity: "ä¼ è¯´"
  c12:
    name: "å´äº¬"
    description: "I'm æ‹†è…»å­ï¼"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/537fb527b952d69dcaac7e90d20faa5f-Full.webp?w=1080&h=1920"
    rarity: "æ™®é€š"
  c13:
    name: "Megamind"
    description: "No bitches?"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/cee2c9554de4068ceef2b4f928830449-Full.webp?w=750&h=627"
    rarity: "ç¨€æœ‰"
  c14:
    name: "Robert Downey Jr"
    description: "Now I am a card."
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/6a99faf289c27fb025dedcdc01ae644f-Full.webp?w=800&h=450"
    rarity: "ç¨€æœ‰"
  c15:
    name: "Jerma"
    description: "When the impostor is sus!ğŸ˜³"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/1693bd37670b42be99d856c7c71856ed-Full.webp?w=250&h=210"
    rarity: "ç¨€æœ‰"
  c16:
    name: "ç–«ä¸¥ä¸çœŸ"
    description: "é‰´å®šä¸ºï¼šæ— ç "
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/c3dc59b3c81787ed361ec83a99886028-Full.webp?w=629&h=760"
    rarity: "æ™®é€š"
  c17:
    name: "ç–«æºä¸çœŸ"
    description: "é‰´å®šä¸ºï¼šæœ‰ç—…"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/58e00a433ed3ccb7238b945a6624f6e1-Full.webp?w=900&h=1200"
    rarity: "æ™®é€š"
  c18:
    name: "è¯‘è¨€ä¸çœŸ"
    description: "é‰´å®šä¸ºï¼šbug"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/74d849c2473be8b29c888be3b3eca5ca-Full.webp?w=960&h=720"
    rarity: "æ™®é€š"
  c19:
    name: "ç‹æ´ªæ–‡"
    description: "å¾ˆé…·ï¼Œä¸èŠå¤©"
    imageUrl: "https://s3-us-west-2.amazonaws.com/www.guilded.gg/ContentMedia/bb69bdd1880993ae942144140c7bccec-Full.webp?w=300&h=300"
    rarity: "å²è¯—"
